module.exports.ProcessSensor = require('./lib/ProcessSensor.js')
module.exports.Sensor = require('./lib/Sensor.js')
module.exports.SensorsServer = require('./lib/SensorsServer.js')
module.exports.SensorUtils = require('./lib/SensorUtils.js')
module.exports.SensorsServerTest = require('./lib/SensorsServerTest.js')